/*******************************************************************************
* File Name: cyfitter_sysint_cfg.c
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_sysint.h"
#include "cyfitter_sysint_cfg.h"

/* ARM CM4 */
#if (((__CORTEX_M == 4) && (CY_CORE_ID == 0)))

    /* I2Cm_SCB_IRQ */
    const cy_stc_sysint_t I2Cm_SCB_IRQ_cfg = {
        .intrSrc = (IRQn_Type)I2Cm_SCB_IRQ__INTC_NUMBER,
        .intrPriority = I2Cm_SCB_IRQ__INTC_CORTEXM4_PRIORITY
    };

    /* DEBUG_UART_SCB_IRQ */
    const cy_stc_sysint_t DEBUG_UART_SCB_IRQ_cfg = {
        .intrSrc = (IRQn_Type)DEBUG_UART_SCB_IRQ__INTC_NUMBER,
        .intrPriority = DEBUG_UART_SCB_IRQ__INTC_CORTEXM4_PRIORITY
    };

    /* SysInt_AnyMotionINT */
    const cy_stc_sysint_t SysInt_AnyMotionINT_cfg = {
        .intrSrc = (IRQn_Type)SysInt_AnyMotionINT__INTC_NUMBER,
        .intrPriority = SysInt_AnyMotionINT__INTC_CORTEXM4_PRIORITY
    };

#endif /* ((__CORTEX_M == 4) && (CY_CORE_ID == 0)) */

