/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* I2Cm_SCB_IRQ */
#define I2Cm_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define I2Cm_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define I2Cm_SCB_IRQ__INTC_NUMBER 44u
#define I2Cm_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define I2Cm_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define I2Cm_SCB_IRQ_INTC_NUMBER 44u

/* DEBUG_UART_SCB_IRQ */
#define DEBUG_UART_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define DEBUG_UART_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define DEBUG_UART_SCB_IRQ__INTC_NUMBER 46u
#define DEBUG_UART_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define DEBUG_UART_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define DEBUG_UART_SCB_IRQ_INTC_NUMBER 46u

/* SysInt_AnyMotionINT */
#define SysInt_AnyMotionINT__INTC_CORTEXM4_ASSIGNED 1
#define SysInt_AnyMotionINT__INTC_CORTEXM4_PRIORITY 7u
#define SysInt_AnyMotionINT__INTC_NUMBER 122u
#define SysInt_AnyMotionINT_INTC_CORTEXM4_ASSIGNED 1
#define SysInt_AnyMotionINT_INTC_CORTEXM4_PRIORITY 7u
#define SysInt_AnyMotionINT_INTC_NUMBER 122u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
